
services:
    - type: web
    name: kord-bot
    env: node
    buildCommand: npm install
    startCommand: node index.js
    autoDeploy: true
    envVars:
            - key: SESSION_ID
        sync: false
            - key: OWNER_NUMBER
        sync: false
            - key: WORKTYPE
        sync: false
            - key: PREFIX
        sync: false
            - key: TIMEZONE
        sync: false
            - key: OWNER_NAME
        sync: false
            - key: BOT_NAME
        sync: false
